services:
  sveltekit:
    build: ./sveltekit
    image: pfaucet.azurecr.io/containergroup:sveltekit_frontend
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
  pocketbase:
    build: ./pocketdb
    image: pfaucet.azurecr.io/containergroup:pocketbase_backend
    ports:
      - 8090:8090
