networks:
  caddy:
services:
  sveltekit:
    build: ./sveltekit
    image: pfaucet.azurecr.io/containergroup:sveltekit_frontend
    env_file:
      - ./.env.production
    ports:
      - 8080:8080
    networks:
      - caddy
    domainname: "pfaucet"
  pocketbase:
    build: ./pocketbase
    image: pfaucet.azurecr.io/containergroup:pocketbase_backend
    ports:
      - 8090:8090
    volumes:
      - pocketbase-volume:/app/data
    networks:
      - caddy
  caddy: 
    image: caddy:latest
    ports:
      - 80:80
      - 443:443
      - 8091:8091
    volumes:
      - caddy-caddyfile:/etc/caddy
      - caddy-data:/data
      - caddy-config:/config
    networks:
      - caddy

volumes:
  caddy-data:
    driver: azure_file
    driver_opts:
      share_name: data
      storage_account_name: caddystorageaccount
  caddy-config:
    driver: azure_file
    driver_opts:
      share_name: config
      storage_account_name: caddystorageaccount
  caddy-caddyfile:
    driver: azure_file
    driver_opts:
      share_name: caddyfile
      storage_account_name: caddystorageaccount
  pocketbase-volume:
    driver: azure_file
    driver_opts:
      share_name: pffileshare
      storage_account_name: pfstorageaccount