services:
  sveltekit:
    build: ./sveltekit
    image: pfaucet.azurecr.io/containergroup:sveltekit_frontend
    env_file:
      - ./sveltekit/.env
    ports:
      - 3000:3000
      - 80:80
  pocketbase:
    build: ./pocketdb
    image: pfaucet.azurecr.io/containergroup:pocketbase_backend
    ports:
      - 8090:8090
    volumes:
      - pocketbase-volume:/app/data

volumes:
  pocketbase-volume:
    driver: azure_file
    driver_opts:
      share_name: pffileshare
      storage_account_name: pfstorageaccount
